import type { Metadata } from "next";
import {
  Changa_One,
  EB_Garamond,
  Geist,
  Geist_Mono,
  Habibi,
} from "next/font/google";
import "./globals.css";

const fontSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = Habibi({
  variable: "--font-mono",
  weight: ["400"],
  subsets: ["latin"],
});

// custom font
const fontHero = Changa_One({
  variable: "--font-hero",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Neza Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontMono.variable} ${fontHero.variable} h-full antialiased bg-white text-gray-700`}
    >
      <body className="font-sans">{children}</body>
    </html>
  );
}
